"use client";
import { useEffect, useMemo, useState } from "react";
import { getItem, getItems, getOutlets, getOverview, getPeople, getPerson, searchMedia, MediaItem, Person, SourceState } from "../lib/api";
import { configuredTabs, TAB_CATALOG, TabId } from "../lib/workbench";

function formatDuration(seconds:number|null){ if(seconds==null)return "duration unavailable"; const hours=Math.floor(seconds/3600),minutes=Math.floor((seconds%3600)/60),secs=seconds%60; return hours?`${hours}h ${minutes}m`:minutes?`${minutes}m ${secs}s`:`${secs}s`; }
function when(value:string|null){ return value?new Date(value).toLocaleString():"not observed"; }
function pct(value:number|undefined){ return `${Math.round((value??0)*100)}%`; }

export default function Page(){
 const tabs=useMemo(()=>configuredTabs(),[]);
 const [active,setActive]=useState<TabId>(tabs[0]);
 const [selectedVideo,setSelectedVideo]=useState<string|null>(null);
 const [selectedPerson,setSelectedPerson]=useState<string|null>(null);
 const [overview,setOverview]=useState<Awaited<ReturnType<typeof getOverview>>|null>(null);
 const [outlets,setOutlets]=useState<SourceState[]>([]);
 const [items,setItems]=useState<MediaItem[]>([]);
 const [people,setPeople]=useState<Person[]>([]);
 const [detail,setDetail]=useState<Awaited<ReturnType<typeof getItem>>|null>(null);
 const [personDetail,setPersonDetail]=useState<Awaited<ReturnType<typeof getPerson>>|null>(null);
 const [query,setQuery]=useState("");
 const [searchResult,setSearchResult]=useState<Awaited<ReturnType<typeof searchMedia>>|null>(null);
 const [error,setError]=useState<string|null>(null);

 useEffect(()=>{
   const params=new URLSearchParams(window.location.search); const requested=params.get("tab") as TabId|null; const video=params.get("video"); const person=params.get("person"); const q=params.get("q")||"";
   if(requested&&tabs.includes(requested))setActive(requested); if(video){setSelectedVideo(video);if(tabs.includes("item"))setActive("item");} if(person){setSelectedPerson(person);if(tabs.includes("people"))setActive("people");} if(q){setQuery(q);searchMedia(q).then(setSearchResult).catch(r=>setError(String(r)));}
   Promise.all([getOverview(),getOutlets(),getItems(),getPeople()]).then(([o,os,is,ps])=>{setOverview(o);setOutlets(os.outlets);setItems(is.items);setPeople(ps.people);}).catch(r=>setError(String(r)));
 },[tabs]);
 useEffect(()=>{ if(!selectedVideo){setDetail(null);return;} getItem(selectedVideo).then(setDetail).catch(r=>setError(String(r))); },[selectedVideo]);
 useEffect(()=>{ if(!selectedPerson){setPersonDetail(null);return;} getPerson(selectedPerson).then(setPersonDetail).catch(r=>setError(String(r))); },[selectedPerson]);
 function navigate(tab:TabId, options?:{video?:string;person?:string}){ setActive(tab); if(options?.video)setSelectedVideo(options.video); if(options?.person)setSelectedPerson(options.person); const params=new URLSearchParams();params.set("tab",tab);if(options?.video)params.set("video",options.video);if(options?.person)params.set("person",options.person);if(tab==="search"&&query)params.set("q",query);window.history.replaceState(null,"",`?${params.toString()}`); }
 async function runSearch(){ try{const result=await searchMedia(query);setSearchResult(result);navigate("search");}catch(r){setError(String(r));} }
 const personById=Object.fromEntries(people.map(person=>[person.person_id,person]));

 return <main><header className="header"><div><div className="kicker">MEDIA MONITOR · M4</div><h1>Media Intelligence Workbench</h1><p>Recent publisher activity, governed text/segments and evidence-bearing expert appearances from configured YouTube channels.</p></div><div className="metrics"><span>{overview?.source_count??"—"} outlets</span><span>{overview?.item_count??"—"} items</span><span>{overview?.text_asset_count??"—"} text states</span><span>{overview?.appearance_count??"—"} appearances</span></div></header>
 <nav>{tabs.map(tab=><button key={tab} className={active===tab?"active":""} onClick={()=>navigate(tab)}>{TAB_CATALOG[tab].label}</button>)}</nav>{error&&<section className="panel error">{error}</section>}

 {active==="latest"&&<section className="panel"><div className="section-head"><div><div className="badge source">SOURCE</div><h2>Latest publisher activity</h2></div><p>{TAB_CATALOG.latest.description}</p></div><div className="list">{items.map(item=><article className="row" key={item.item_uid}><div><div className="eyebrow">{item.outlet?.display_name||item.source_id} · {when(item.published_at)}</div><h3>{item.title}</h3><p>{formatDuration(item.duration_seconds)} · text: <strong>{item.text_status||"not_attempted"}</strong> · {item.appearance_count??0} detected appearance{item.appearance_count===1?"":"s"}</p></div><button onClick={()=>navigate("item",{video:item.native_id})}>Open item</button></article>)}</div></section>}

 {active==="people"&&<section className="panel"><div className="section-head"><div><div className="badge detection">DETECTION</div><h2>People</h2></div><p>Configured identities only. Each appearance retains the exact evidence source and alias that produced the match.</p></div>{!selectedPerson&&<div className="cards">{people.map(person=><article className="card" key={person.person_id}><h3>{person.display_name}</h3><p>{person.appearance_count} appearances · {person.outlet_count} outlets</p><p>Aliases: {person.aliases.join(", ")}</p><button onClick={()=>navigate("people",{person:person.person_id})}>Open appearances</button></article>)}</div>}{selectedPerson&&personDetail&&<><button onClick={()=>{setSelectedPerson(null);setPersonDetail(null);window.history.replaceState(null,"","?tab=people");}}>← All people</button><h3>{personDetail.person.display_name}</h3><div className="list">{personDetail.appearances.map(row=><article className="row" key={row.appearance.appearance_id}><div><div className="eyebrow">{row.outlet?.display_name||row.item.source_id} · {when(row.item.published_at)}</div><h3>{row.item.title}</h3><p><strong>DETECTION</strong> · {row.appearance.evidence_source} · matched “{row.appearance.matched_alias}”</p></div><button onClick={()=>navigate("item",{video:row.item.native_id})}>Open item</button></article>)}</div></>}</section>}

 {active==="outlets"&&<section className="panel"><div className="section-head"><div><div className="badge monitor">MONITOR</div><h2>Outlets</h2></div><p>Health is reconciliation health, not a claim that the publisher must upload every day.</p></div><div className="cards">{outlets.map(outlet=><article className="card" key={outlet.source_id}><h3>{outlet.display_name}</h3><p><strong>{outlet.health}</strong></p><dl><dt>Last reconciliation</dt><dd>{when(outlet.last_success_at)}</dd><dt>Latest publication</dt><dd>{when(outlet.latest_published_at)}</dd><dt>Observed items</dt><dd>{outlet.item_count}</dd><dt>Governed text coverage</dt><dd>{pct(outlet.text_coverage)}</dd></dl></article>)}</div></section>}

 {active==="search"&&<section className="panel"><div className="section-head"><div><div className="badge detection">INSPECTION</div><h2>Search</h2></div><p>Literal search only. Metadata is always searchable; governed text contributes only when an allowed text asset exists.</p></div><div className="search-row"><input aria-label="Search media" value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")void runSearch();}}/><button onClick={()=>void runSearch()}>Search</button></div>{searchResult&&<><p>Capability: <code>{searchResult.capability}</code> · {searchResult.count} result{searchResult.count===1?"":"s"}</p><div className="list">{searchResult.hits.map(hit=><article className="row" key={hit.item_uid}><div><div className="eyebrow">{hit.outlet?.display_name||hit.source_id} · {when(hit.published_at)}</div><h3>{hit.title}</h3><p>Evidence: {hit.evidence.map(e=>e.source+(e.status?` (${e.status})`:"")).join(", ")}</p></div><button onClick={()=>navigate("item",{video:hit.native_id})}>Open item</button></article>)}</div></>}</section>}

 {active==="item"&&<section className="panel">{!selectedVideo&&<p>Select an item from Latest, People or Search.</p>}{selectedVideo&&!detail&&<p>Loading item…</p>}{detail&&<><div className="section-head"><div><div className="badge source">SOURCE</div><h2>{detail.item.title}</h2><p>{detail.outlet?.display_name} · {when(detail.item.published_at)} · {formatDuration(detail.item.duration_seconds)}</p></div><a className="button-link" href={detail.item.canonical_url} target="_blank" rel="noreferrer">Open on YouTube ↗</a></div><div className="description">{detail.item.description||"Description empty upstream."}</div><div className="evidence-grid"><section><div className="badge source">SOURCE</div><h3>YouTube metadata</h3><p>Native video ID: <code>{detail.item.native_id}</code></p><p>Publisher URL remains canonical evidence.</p></section><section><div className="badge monitor">MONITOR</div><h3>Observed state</h3><p>Item UID: <code>{detail.item.item_uid}</code></p><p>First seen: {when(detail.item.first_seen)}</p><p>Last seen: {when(detail.item.last_seen)}</p><p>{detail.snapshot_count} immutable metadata state{detail.snapshot_count===1?"":"s"}</p></section></div>
 <section className="text-state"><div className="badge monitor">CORPUS</div><h3>Text provenance</h3><p><strong>{detail.text_enrichment.status}</strong> · {detail.text_enrichment.available?"searchable governed text":"no searchable governed text"}</p><p>{detail.text_enrichment.message}</p>{detail.text_assets.filter(asset=>asset.text).map(asset=><details key={asset.text_asset_id}><summary>{asset.status} · {asset.acquisition_method}</summary><p>{asset.text}</p><code>{asset.text_sha256}</code></details>)}</section>
 <section><div className="badge monitor">SEGMENTS</div><h3>Content boundaries</h3><div className="list">{detail.segments.map(segment=><article className="row" key={segment.segment_id}><div><strong>{segment.label||segment.boundary_source}</strong><p>{formatDuration(segment.start_seconds)} → {formatDuration(segment.end_seconds)} · {segment.boundary_source}</p></div></article>)}</div></section>
 <section><div className="badge detection">DETECTION</div><h3>Appearances</h3>{detail.appearances.length===0?<p>No configured-person appearance detected.</p>:detail.appearances.map(appearance=><p key={appearance.appearance_id}><strong>{personById[appearance.person_id]?.display_name||appearance.person_id}</strong> · {appearance.evidence_source} · matched “{appearance.matched_alias}”</p>)}</section>
 <details><summary>Metadata snapshot history ({detail.snapshot_count})</summary><pre>{JSON.stringify(detail.metadata_snapshots,null,2)}</pre></details></>}</section>}
 </main>;
}
