"use client";
import { useEffect, useMemo, useState } from "react";
import { getItem, getItems, getOutlets, getOverview, MediaItem, SourceState } from "../lib/api";
import { configuredTabs, TAB_CATALOG, TabId } from "../lib/workbench";
function formatDuration(seconds:number|null){ if(seconds==null)return "duration unavailable"; const hours=Math.floor(seconds/3600),minutes=Math.floor((seconds%3600)/60),secs=seconds%60; return hours?`${hours}h ${minutes}m`:minutes?`${minutes}m ${secs}s`:`${secs}s`; }
function when(value:string|null){ return value?new Date(value).toLocaleString():"not observed"; }
export default function Page(){
 const tabs=useMemo(()=>configuredTabs(),[]); const [active,setActive]=useState<TabId>(tabs[0]); const [selectedVideo,setSelectedVideo]=useState<string|null>(null); const [overview,setOverview]=useState<Awaited<ReturnType<typeof getOverview>>|null>(null); const [outlets,setOutlets]=useState<SourceState[]>([]); const [items,setItems]=useState<MediaItem[]>([]); const [detail,setDetail]=useState<Awaited<ReturnType<typeof getItem>>|null>(null); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{ const params=new URLSearchParams(window.location.search); const requested=params.get("tab") as TabId|null; const video=params.get("video"); if(requested&&tabs.includes(requested))setActive(requested); if(video){setSelectedVideo(video);if(tabs.includes("item"))setActive("item");} Promise.all([getOverview(),getOutlets(),getItems()]).then(([o,os,is])=>{setOverview(o);setOutlets(os.outlets);setItems(is.items);}).catch(r=>setError(String(r))); },[tabs]);
 useEffect(()=>{ if(!selectedVideo){setDetail(null);return;} getItem(selectedVideo).then(setDetail).catch(r=>setError(String(r))); },[selectedVideo]);
 function navigate(tab:TabId,video?:string){ setActive(tab); if(video)setSelectedVideo(video); const params=new URLSearchParams();params.set("tab",tab);if(video)params.set("video",video);window.history.replaceState(null,"",`?${params.toString()}`); }
 return <main><header className="header"><div><div className="kicker">MEDIA MONITOR · M1-P</div><h1>Channel Monitor</h1><p>Recent publisher activity from configured YouTube channels, reconciled through stable platform identity.</p></div><div className="metrics"><span>{overview?.source_count??"—"} outlets</span><span>{overview?.item_count??"—"} items</span><span>{overview?.snapshot_count??"—"} snapshots</span></div></header>
 <nav>{tabs.map(tab=><button key={tab} className={active===tab?"active":""} onClick={()=>navigate(tab)}>{TAB_CATALOG[tab].label}</button>)}</nav>{error&&<section className="panel error">{error}</section>}
 {active==="latest"&&<section className="panel"><div className="section-head"><div><div className="badge source">SOURCE</div><h2>Latest publisher activity</h2></div><p>{TAB_CATALOG.latest.description}</p></div><div className="list">{items.map(item=><article className="row" key={item.item_uid}><div><div className="eyebrow">{item.outlet?.display_name||item.source_id} · {when(item.published_at)}</div><h3>{item.title}</h3><p>{formatDuration(item.duration_seconds)} · text enrichment not attempted in M1</p></div><button onClick={()=>navigate("item",item.native_id)}>Open item</button></article>)}</div></section>}
 {active==="outlets"&&<section className="panel"><div className="section-head"><div><div className="badge monitor">MONITOR</div><h2>Outlets</h2></div><p>Health is reconciliation health, not a claim that the publisher must upload every day.</p></div><div className="cards">{outlets.map(outlet=><article className="card" key={outlet.source_id}><h3>{outlet.display_name}</h3><p><strong>{outlet.health}</strong></p><dl><dt>Last reconciliation</dt><dd>{when(outlet.last_success_at)}</dd><dt>Latest publication</dt><dd>{when(outlet.latest_published_at)}</dd><dt>Observed items</dt><dd>{outlet.item_count}</dd><dt>API calls</dt><dd>{outlet.api_calls}</dd></dl></article>)}</div></section>}
 {active==="item"&&<section className="panel">{!selectedVideo&&<p>Select an item from Latest.</p>}{selectedVideo&&!detail&&<p>Loading item…</p>}{detail&&<><div className="section-head"><div><div className="badge source">SOURCE</div><h2>{detail.item.title}</h2><p>{detail.outlet?.display_name} · {when(detail.item.published_at)} · {formatDuration(detail.item.duration_seconds)}</p></div><a className="button-link" href={detail.item.canonical_url} target="_blank" rel="noreferrer">Open on YouTube ↗</a></div><div className="description">{detail.item.description||"Description empty upstream."}</div><div className="evidence-grid"><section><div className="badge source">SOURCE</div><h3>YouTube metadata</h3><p>Native video ID: <code>{detail.item.native_id}</code></p><p>Publisher URL remains canonical evidence.</p></section><section><div className="badge monitor">MONITOR</div><h3>Observed state</h3><p>Item UID: <code>{detail.item.item_uid}</code></p><p>First seen: {when(detail.item.first_seen)}</p><p>Last seen: {when(detail.item.last_seen)}</p><p>{detail.snapshot_count} immutable metadata state{detail.snapshot_count===1?"":"s"}</p></section></div><section className="text-state"><h3>Text enrichment</h3><p><strong>Not attempted in M1.</strong> Missing transcript is not a monitoring failure.</p></section><details><summary>Metadata snapshot history ({detail.snapshot_count})</summary><pre>{JSON.stringify(detail.metadata_snapshots,null,2)}</pre></details></>}</section>}</main>;
}
