const API_BASE = process.env.NEXT_PUBLIC_CHANNEL_MONITOR_API_BASE || "http://127.0.0.1:9100";
export type SourceState = { source_id:string; display_name:string; channel_id:string; channel_title:string; last_attempt_at:string; last_success_at:string|null; latest_published_at:string|null; health:string; error:string|null; item_count:number; api_calls:number; quota_units_estimated:number; text_available_count?:number; text_coverage?:number; };
export type MediaItem = { item_uid:string; source_id:string; native_id:string; canonical_url:string; title:string; description:string; published_at:string; duration_seconds:number|null; first_seen:string; last_seen:string; outlet?:SourceState|null; text_status?:string; text_available?:boolean; appearance_count?:number; segment_count?:number; };
export type Person = { person_id:string; display_name:string; aliases:string[]; appearance_count:number; outlet_count:number; };
export type Appearance = { appearance_id:string; person_id:string; item_uid:string; segment_id:string|null; evidence_source:string; matched_alias:string; confidence:number|null; observed_at:string; };
export type TextAsset = { text_asset_id:string; item_uid:string; status:string; acquisition_method:string; language:string|null; timing_available:boolean; text:string|null; text_sha256:string|null; observed_at:string; generator:{provider:string;model:string}|null; };
export type Segment = { segment_id:string; item_uid:string; start_seconds:number; end_seconds:number; boundary_source:string; label:string|null; text_asset_id:string|null; confidence:number|null; };
async function read<T>(path:string):Promise<T>{ const response=await fetch(`${API_BASE}${path}`,{cache:"no-store"}); if(!response.ok) throw new Error(`${path} ${response.status}`); return response.json() as Promise<T>; }
export async function getOverview(){ return read<{source_count:number;item_count:number;snapshot_count:number;text_asset_count:number;segment_count:number;appearance_count:number;person_count:number;sources:SourceState[];text_enrichment:string}>("/api/channel-monitor"); }
export async function getOutlets(){ return read<{outlets:SourceState[]}>("/api/outlets"); }
export async function getItems(sourceId?:string){ const suffix=sourceId?`?source_id=${encodeURIComponent(sourceId)}&limit=100`:"?limit=100"; return read<{items:MediaItem[];count:number}>(`/api/items${suffix}`); }
export async function getItem(videoId:string){ return read<{item:MediaItem;outlet:SourceState|null;metadata_snapshots:Array<Record<string,unknown>>;snapshot_count:number;text_enrichment:{status:string;available:boolean;message:string};text_assets:TextAsset[];segments:Segment[];appearances:Appearance[]}>(`/api/items/${encodeURIComponent(videoId)}`); }
export async function getPeople(){ return read<{people:Person[]}>("/api/people"); }
export async function getPerson(personId:string){ return read<{person:Omit<Person,"appearance_count"|"outlet_count">;appearance_count:number;appearances:Array<{appearance:Appearance;item:MediaItem;outlet:SourceState|null}>}>(`/api/people/${encodeURIComponent(personId)}`); }
export async function searchMedia(query:string){ return read<{query:string;capability:string;count:number;hits:Array<{item_uid:string;native_id:string;title:string;published_at:string;source_id:string;outlet:SourceState|null;evidence:Array<{source:string;text_asset_id?:string|null;status?:string}>}>}>(`/api/search?q=${encodeURIComponent(query)}&limit=50`); }
