schema_version: southland_aliases.v1
aliases:
  - real_name: "Javier Milei"
    southland_name: "Javier Mieli"
  - real_name: "Karina Milei"
    southland_name: "Karina Mieli"
  - real_name: "Luis Caputo"
    southland_name: "Toto Capuccino"
  - real_name: "Nicolás \"Nicky\" Caputo"
    southland_name: "Nicky Macchiato"
  - real_name: "Patricia Bullrich"
    southland_name: "Patricia Bulldog"
  - real_name: "Axel Kicillof"
    southland_name: "Axel Kicillofsky"
  - real_name: "Sergio Massa"
    southland_name: "Sergio Masa Madre"
  - real_name: "Cristina Fernández de Kirchner"
    southland_name: "Cristina Fernández de Kirsch"
  - real_name: "Máximo Kirchner"
    southland_name: "Máximo Kirsch"
  - real_name: "Mariano Recalde"
    southland_name: "Mariano Recalcula"
  - real_name: "Paula Penacca"
    southland_name: "Paula Península"
  - real_name: "Raúl Jalil"
    southland_name: "Raúl Jalapeño"
  - real_name: "Gustavo Sáenz"
    southland_name: "Gustavo Sáenzwich"
  - real_name: "Ariel Lijo"
    southland_name: "Ariel Legajo"
  - real_name: "Martín Llaryora"
    southland_name: "Martín Llavero"
  - real_name: "Maximiliano Pullaro"
    southland_name: "Maxi Pulóver"
  - real_name: "Ignacio \"Nacho\" Torres"
    southland_name: "Nacho Torrejas"
  - real_name: "Juan Schiaretti"
    southland_name: "Juan Schiarettini"
  - real_name: "Diego Santilli"
    southland_name: "Diego Santillín"
  - real_name: "Manuel Adorni"
    southland_name: "Manuel Adorno"
  - real_name: "Martín Menem"
    southland_name: "Martín Menú"
  - real_name: "Lucía Corpacci"
    southland_name: "Lucía Carpaccio"
  - real_name: "Emilia Orozco"
    southland_name: "Emilia Oráculo"
  - real_name: "Casa Rosada"
    southland_name: "Casa Fucsia"
